### ISSUE TITLE
TileProvider documentation does not show up

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace-Documentation#1]
![image](https://github.com/OpenSpace/OpenSpace-Documentation/assets/4921724/c8e59aba-d389-4823-86ae-74dcea5c6c8b)

Tested on OpenSpace/OpenSpace@bb9a3e375d5fdadce05decdad911dce440ffcd34

**Comment by ylvaselling** [comment]
Fixed 
![image](https://github.com/OpenSpace/OpenSpace-Documentation/assets/24265984/936c71ab-07cf-47d0-959c-58e8cb4ba14f)
